### PR TITLE
fix somes viscious errors

### PR DESCRIPTION
**Pull request by szorfein**
Hi, i back after some test, i wrote a little wiki on my repository
[Gentoo-ZFS](https://github.com/szorfein/Gentoo-ZFS/wiki/gentoo-zfs)

but i have found some problems for generate initramfs correctly.

## Part 1 - tools:

    cd /usr/share/mkinitramfs-ll/scripts
    
    ./busybox -d /usr/share/mkinitramfs-ll/usr
    ...compilation work...

    ./gnupg -d /usr/share/mkinitramfs-ll/usr
    Fail return on argument without anything.

Work too after my [commit](https://github.com/szorfein/mkinitramfsll/commit/9be7b14ff3599011986e3c9aa14d6ad69cdba4f9)

I generate initramfs with command
    
    mkinitramfs-ll.sh --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --extension=img --keymap=fr-  latin9
    bin/uncompress applet not found, no suitable busybox found

I say WTF, i look busybox compiled with +mdev +pam +systemd only.

    ls /usr/share/mkinitramfs-ll/usr/lib
    nothing (only directory mdev mkinitramfs-ll, normal...)

After it, i use my little script non-static-busybox.sh who copied this files.

    ./non-static-busybox.sh
    ls /usr/share/mkinitramfs-ll/usr/lib
    ld-linux-x86-64.so.2 libc.so.6 libdl.so.2 libpam_misc.so.0 libpam.so.0

I regenerate again initramfs (same command) and all work, reboot work fine too (on BIOS), all work perfectly.

## Part 2 - Test on generate Initrd.

I try with both option --compressor=none and --extension=img.

### First try:

    mkinitramfs-ll.sh --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --compressor=none -- extension=img --keymap=fr-latin9
    /usr/sbin/mkinitramfs-ll.sh: line 111: -c: command not found
    Failed to build /boot/initramfs-4.7.10-hardened-r2.cpio.img initramfs

### Second try without --compressor:

    mkinitramfs-ll.sh --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --extension=img --keymap=fr-latin9
    
work...but

    file /boot/initramfs-4.7.10-hardened-r2.img return: XZ compressed data

It work on EFI system?

### last try without --extension:

    mkinitramfs-ll.sh --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --compressor=none --keymap=fr-latin9

work...too

    file /boot/initramfs-4.7.10-hardened-r2.cpio return: ASCII cpio archive (SVR4 with no CRC)
    it sure it work but i must edit grub.cfg manually.

Fix too with [last commit](https://github.com/szorfein/mkinitramfs-ll/commit/ab0c73918bee8905dcf28d5ea15956d6b6d96082)

### CODE REVIEW

**Comment by tokiclover** [comment]
I don't see any need to add that extra library again as I've already said last time. You should know if you looked at the script that there is already a function to copy library... So, if it doesn't work as expected post your command prefixed with `/bin/sh -x` so the issue can be solved instead of insisting to include that extra shell library.

Second, only [commit](https://github.com/szorfein/mkinitramfs-ll/commit/ab0c73918bee8905dcf28d5ea15956d6b6d96082) is merge-able...

I see where you're having the extension issue again... that commit is not needed: you're specifying `--extension=img` without the `cpio.` prefix which get the script confused. And it that wasn't enough, you're asking to add more confusion by using `$ext` instead of `$extension` which is wrong.

The other commits won't be merged because they are coming from an old PR which is not wanted since the paths are properly set with the installation.

You should clear/reset (with `git reset HEAD~$NUMBER` for example) some commits on your fork to be able to send new PRs. That's why one has to use a private branch for your personal developments if it's not strictly fixes that can be merged.

**Comment by tokiclover** [comment]
NOTE: `git reset --hard HEAD~$NUMBER` or `git reset --hard $COMMIT` because I won't be merging the old commit from the previous PR which was already addressed.

**Comment by tokiclover** [comment]
Sorry for... it seems you're right with the `$ext` use instead of `$extension`... but that grub switch is not needed at all.

**Comment by tokiclover** [comment]
So, all in all, only [1f46fc5373](https://github.com/tokiclover/mkinitramfs-ll/pull/43/commits/1f46fc53736c99f2ca21351157904d0692df2d42), [9be7b14ff](https://github.com/tokiclover/mkinitramfs-ll/pull/43/commits/9be7b14ff3599011986e3c9aa14d6ad69cdba4f9) and [ab0c73918](https://github.com/tokiclover/mkinitramfs-ll/pull/43/commits/ab0c73918bee8905dcf28d5ea15956d6b6d96082).

**Comment by tokiclover** [comment]
So, poste `/bin/sh -x /usr/sbin/mkinitramfs-ll.sh --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --extension=img --keymap=fr-latin1` to be done with that busybox issue.

**Comment by szorfein** [comment]
yes only 3 last commit, sorry about script non-static-busybox, i wouldn't commit it again..., i don't know how make pull request with certains commit.  
I need look somes wiki about github..:).

**Comment by tokiclover** [comment]
It's not necessary to post the shell trace because the issue shall be fixed with 60b5980.
Actually, you need to make PR from another branch rather than master because... because if ever the PR is rejected you shall reset your commits with `git rset --hard...` command which is rarely used--well, you should not use it. But now, you have to because your commits cannot be merged. If you have made the commit from another branch, you could just merge the particular commits instead of all with `git merge $COMMITS` which you would not have to if the commits were merged from upstream.

So, you have to real reset every commits you've made and redo new commits to be able to make a new PR. Sorry for that... but you have to learn to use git.

**Comment by szorfein** [comment]
i test with [60b5980](https://github.com/tokiclover/mkinitramfs-ll/commit/60b5980943d45d4c35af7e533c14750be69f5cbc)

**Comment by tokiclover** [comment]
Are you doing the commit from github web interface? If so, I don't know how to reset the commits from there. However, you can have your local copy of your fork by running `git clone git://github.com/szorfein/mkinit-ramfs-ll.git`, then install git with `emerge -av git` and then doing what I've said above, so to speak, run `git reset --hard $COMMIT` and then recommit.

You shall learn to use git on your local machine instead of github!

**Comment by szorfein** [comment]
it's what i do, all in console :), i make pull request only with web interface, but i will look more about that )
I have again same error with you last commit

**Comment by szorfein** [comment]
+ name=mkinitramfs-ll
+ package=mkinitramfs-ll
+ shell=sh
+ version=0.22.0
+ null=/dev/null
+ '[' -f /etc/mkinitramfs-ll.conf ']'
+ source /etc/mkinitramfs-ll.conf
++ module_boot='kms ext2 ext3 ext4'
++ module_device_mapper=device-mapper
++ module_dm_crypt='aes dm-crypt sha256 sha512 wp512 ecb lrw xts twofish serpent'
++ module_dm_raid='dm-raid dm-mirror dm-multipath dm-snapshot'
++ module_gpg=cast5
++ module_kms='i915 nouveau radeon'
++ module_raid='raid0 raid10 raid1 raid456'
++ module_remdev='nls_cp437 vfat'
++ module_squashd='aufs overlay squashfs'
++ module_swsusp=
++ module_tuxonice='tuxonice_swap tuxonice_userui tuxonice_file'
++ module_zfs=zfs
++ module_zram=zram
++ module_bcache=bcache
++ module_btrfs=btrfs
++ modules=uvesafb
++ module_group='boot kms remdev swsusp'
++ bins='blkid v86d'
++ bin_zfs='zfs zpool'
++ bin_btrfs='btrfs btrfsck fsck.btrfs'
++ fonts='ter-g12n ter-g14n ter-112n ter-v12n'
++ keymaps='azerty dvorak unicode'
++ env=
++ env=' ENV_CHK=false'
++ env=' ENV_CHK=false root=zfsforninja zfs=3c27c7f8-8728-4bae-8142-2375baafadc5 luks=gpg:UUID=d7ef31f0-8dfa-429d-a705-a10ded828bcb:key.gpg'
++ getopt -o 'ab:c:e:f:F:gk:lH:KLm:p:qrs:thu:y:?' -l all,bin:,compressor:,extension:,firmware:,font:,gpg,help -l hook:,luks,lvm,keep-tmpdir,module:,keymap:,kernel-version: -l module-boot:,module-gpg:,module-remdev:,module-squashd:,module-tuxonice: -l prefix:,rebuild,splash:,squashd,toi,usrdir: -n mkinitramfs-ll -s sh -- --luks --gpg -k 4.7.10-hardened-r2 --hook=zfs --extension=img --keymap=fr-latin9
+ opt=' --luks --gpg -k '\''4.7.10-hardened-r2'\'' --hook '\''zfs'\'' --extension '\''img'\'' --keymap '\''fr-latin9'\'' --'
+ eval set -- --luks --gpg -k ''\''4.7.10-hardened-r2'\''' --hook ''\''zfs'\''' --extension ''\''img'\''' --keymap ''\''fr-latin9'\''' --
++ set -- --luks --gpg -k 4.7.10-hardened-r2 --hook zfs --extension img --keymap fr-latin9 --
+ true
+ case "${1}" in
+ option_luks=:
+ shift
+ true
+ case "${1}" in
+ option_gpg=:
+ shift
+ true
+ case "${1}" in
+ shift
+ kv=4.7.10-hardened-r2
+ shift
+ true
+ case "${1}" in
+ shift
+ hooks=' zfs'
+ shift
+ true
+ case "${1}" in
+ shift
+ extension=img
+ shift
+ true
+ case "${1}" in
+ shift
+ keymaps='fr-latin9 azerty dvorak unicode'
+ shift
+ true
+ case "${1}" in
+ shift
+ break
+ : 4.7.10-hardened-r2
+ : initramfs-
+ : /usr/share/mkinitramfs-ll/usr
+ : initramfs-4.7.10-hardened-r2
+ : xz -9 --check=crc32
++ uname -m
+ : x86_64
++ getconf LONG_BIT
+ : 64
++ mktmp initramfs-4.7.10-hardened-r2
++ local tmp=/tmp/initramfs-4.7.10-hardened-r2-XXXXXX
++ mkdir -p /tmp/initramfs-4.7.10-hardened-r2-XXXXXX
++ echo /tmp/initramfs-4.7.10-hardened-r2-XXXXXX
+ tmpdir=/tmp/initramfs-4.7.10-hardened-r2-XXXXXX
+ confdir=etc/mkinitramfs-ll
+ source /usr/share/mkinitramfs-ll/usr/lib/mkinitramfs-ll/functions
+ eval_colors
+ '[' -t 1 ']'
+ yesno Yes
+ case "${1:-NO}" in
+ return 0
+ local 'BLD=1;' 'ESC=\e[' FGD=3 clr
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_BLK='\''\e[1;30m'\'''
++ export 'COLOR_BLK=\e[1;30m'
++ COLOR_BLK='\e[1;30m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_RED='\''\e[1;31m'\'''
++ export 'COLOR_RED=\e[1;31m'
++ COLOR_RED='\e[1;31m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_GRN='\''\e[1;32m'\'''
++ export 'COLOR_GRN=\e[1;32m'
++ COLOR_GRN='\e[1;32m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_YLW='\''\e[1;33m'\'''
++ export 'COLOR_YLW=\e[1;33m'
++ COLOR_YLW='\e[1;33m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_BLU='\''\e[1;34m'\'''
++ export 'COLOR_BLU=\e[1;34m'
++ COLOR_BLU='\e[1;34m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_MAG='\''\e[1;35m'\'''
++ export 'COLOR_MAG=\e[1;35m'
++ COLOR_MAG='\e[1;35m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_CYN='\''\e[1;36m'\'''
++ export 'COLOR_CYN=\e[1;36m'
++ COLOR_CYN='\e[1;36m'
+ for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT
+ eval export 'COLOR_WHT='\''\e[1;37m'\'''
++ export 'COLOR_WHT=\e[1;37m'
++ COLOR_WHT='\e[1;37m'
+ COLOR_RST='\e[0m'
+ COLOR_BLD='\e[1m'
+ COLOR_UND='\e[4m'
+ COLOR_ITA='\e[3m'
+ export COLOR_RST COLOR_BLD COLOR_ITA COLOR_UND
+ '[' -n '' ']'
+ '[' -n 'ter-g12n ter-g14n ter-112n ter-v12n' -a 'ter-g12n ter-g14n ter-112n ter-v12n' = : -a -e /etc/conf.d/consolefont ']'
+ '[' -n 'fr-latin9 azerty dvorak unicode' -a 'fr-latin9 azerty dvorak unicode' = : -a -e /etc/conf.d/keymaps ']'
+ case "${compressor}" in
+ '[' -e /usr/src/linux-4.7.10-hardened-r2/.config ']'
+ config=/usr/src/linux-4.7.10-hardened-r2/.config
++ type -p grep
+ xgrep=/bin/grep
+ '[' -f /usr/src/linux-4.7.10-hardened-r2/.config ']'
+ comp=xz
++ echo xz
++ tr '[a-z]' '[A-Z]'
+ CONFIG=CONFIG_RD_XZ
+ /bin/grep -q '^CONFIG_RD_XZ=y' /usr/src/linux-4.7.10-hardened-r2/.config
+ unset config xgrep CONFIG comp
+ echo -e '\e[1;34m>>>\e[0m Building initramfs-4.7.10-hardened-r2...'
+ cd /tmp/initramfs-4.7.10-hardened-r2-XXXXXX
+ '[' -n '' ']'
+ rm -fr bin dev etc init lib lib64 mnt newroot proc root run sbin sys usr
+ '[' -d /usr/share/mkinitramfs-ll/usr ']'
+ cp -ar /usr/share/mkinitramfs-ll/usr .
+ mv -f usr/root usr/etc .
+ mv -f usr/lib lib64
+ mkdir -p usr/share/consolefonts usr/share/keymaps usr/lib64 usr/bin usr/sbin sbin bin dev proc sys newroot mnt/tok etc/mkinitramfs-ll etc/splash run lib64/modules/4.7.10-hardened-r2 lib64/mkinitramfs-ll
+ for dir in lib usr/lib
+ ln -s lib64 lib
+ for dir in lib usr/lib
+ ln -s lib64 usr/lib
+ for key in name shell version
+ eval echo 'name=${name}'
++ echo name=mkinitramfs-ll
+ for key in name shell version
+ eval echo 'shell=${shell}'
++ echo shell=sh
+ for key in name shell version
+ eval echo 'version=${version}'
++ echo version=0.22.0
++ date +%Y-%m-%d-%H-%M-%S
+ echo build=2016-11-06-22-18-23
+ touch etc/fstab etc/mtab
+ cp -a /dev/console /dev/random /dev/urandom /dev/mem /dev/null /dev/tty /dev/tty0 /dev/tty1 /dev/tty2 /dev/tty3 /dev/tty4 /dev/tty5 /dev/tty6 /dev/zero dev/
+ major=4
+ minor=7.10-hardened-r2
+ minor=7
+ '[' 4 -eq 3 -a 7 -ge 1 ']'
+ unset major minor
+ cp -a /usr/share/mkinitramfs-ll/usr/../init .
+ chmod 775 init
+ '[' -d root ']'
+ chmod 0700 root
+ cp -af /lib/modules/4.7.10-hardened-r2/modules.dep lib/modules/4.7.10-hardened-r2
+ '[' -n '' ']'
+ for bin in dmraid mdadm zfs
+ case "${bins}" in
+ for bin in dmraid mdadm zfs
+ case "${bins}" in
+ for bin in dmraid mdadm zfs
+ case "${bins}" in
+ module_group='boot kms remdev swsusp'
+ for hook in ${hooks}
+ for file in "${usrdir}"/../hooks/*${hook}*
+ cp -a /usr/share/mkinitramfs-ll/usr/../hooks/mkswap-zfs lib/mkinitramfs-ll/
+ for file in "${usrdir}"/../hooks/*${hook}*
+ cp -a /usr/share/mkinitramfs-ll/usr/../hooks/zfs lib/mkinitramfs-ll/
+ '[' 0 '!=' 0 ']'
+ eval 'bins="blkid v86d ${bin_zfs}"'
++ bins='blkid v86d zfs zpool'
+ module_group='boot kms remdev swsusp zfs'
+ '[' -f /etc/issue.logo ']'
+ cp /etc/issue.logo etc/
+ '[' -x usr/bin/busybox ']'
+ mv -f usr/bin/busybox bin/
+ '[' '!' -f etc/mkinitramfs-ll/busybox.applets ']'
+ bin/busybox --list-full
+ read bin
+ grep -q bin/ash etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/awk etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/blkid etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/bunzip2 etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/bzip2 etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/cat etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/chattr etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/chgrp etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/chmod etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/chown etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/chroot etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/chvt etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/clear etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/cp etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/cpio etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/cut etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/dd etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/diff etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/dirname etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/dmesg etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/dumpkmap etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/ed etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/expr etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/fsck etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/grep etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/gunzip etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/gzip etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/halt etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/head etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/init etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/ln etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/loadfont etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/loadkmap etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/losetup etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/lsattr etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/lzma etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/mdev etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/mkdir etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/mknod etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/modinfo etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/modprobe etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/mount etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/mv etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/openvt etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/patch etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/readlink etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/rm etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/rmdir etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/rmmod etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/sed etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/seq etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/setconsole etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/setfont etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/setkeycodes etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/setlogcons etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/setsid etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/sleep etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q sbin/switch_root etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/tar etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/test etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/tr etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/tty etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/umount etc/mkinitramfs-ll/busybox.applets
+ read bin
+ grep -q bin/uncompress etc/mkinitramfs-ll/busybox.applets
+ die 'bin/uncompress applet not found, no suitable busybox found'
+ local ret=1
+ error 'bin/uncompress applet not found, no suitable busybox found'
+ local 'prefix=\e[1;33mmkinitramfs-ll:\e[0m'
+ echo -e '\e[1;31mERROR:\e[0m\e[1;33mmkinitramfs-ll:\e[0m bin/uncompress applet not found, no suitable busybox found'
[1;31mERROR:[0m[1;33mmkinitramfs-ll:[0m bin/uncompress applet not found, no suitable busybox found
+ exit 1

**Comment by tokiclover** [comment]
The issue if obvious: you have copied a busybox binary to `$usrdir` which is not static! You don't have to do that! In your case you just leave the script handle the usual copy of dynamic linked binary. The library cannot be copied forcibly when a user has copied a binary there because the user shall know what he is doing. Remove everything unnecessary, so busybox to speak and re-run the script. The last commit should be enough for this issue--it was just a matter of a typo which wasn't fixed last time.

**Comment by tokiclover** [comment]
Why don't use the bash script instead? Well, now the sh version is fully tested at least!

**Comment by szorfein** [comment]
i have generate with you're script ./busybox -d /usr/share/mkinitramfs-ll/usr,
i have remove all lib than my script have copied. 
It a true test :)

**Comment by tokiclover** [comment]
I don't understand, do you mean you've made another test? because the last one show 
```
'[' -x usr/bin/busybox ']'
mv -f usr/bin/busybox bin
```
which means that you have copied busybox to `$usrdir`.

**Comment by szorfein** [comment]
yep i have retest
rm /usr/share/mkinitramfs-ll/usr/bin/busybox
rm /usr/share/mkinitramfs-ll/usr/lib/*.so.*
./busybox -d /usr/lib/mkinitramfs-ll/usr/
and you have result uppon :)

**Comment by szorfein** [comment]
but it's ok, for now it work temporary with non-static script, we can found an other solution later.

**Comment by tokiclover** [comment]
It cannot be... see, the particular piece of code is
```
if [ -x usr/bin/busybox ]; then
	mv -f usr/bin/busybox bin/
elif type -p busybox >${null} 2>&1; then
	bb=$(type -p busybox 2>${null})
	if ldd ${bb} >${null} 2>&1; then
		busybox --list-full >${confdir}/busybox.applets
		bins="${bb} ${bins}"
		warn "busybox is not a static binary"
	fi
	cp -a ${bb} bin/
	unset bb
else
	die "No busybox binary found"
fi
if [ ! -f ${confdir}/busybox.applets ]; then
	bin/busybox --list-full >${confdir}/busybox.applets || die
fi
```
so, if busybox is moved from `$usrdir`, it does mean there is a binary there.

**Comment by tokiclover** [comment]
Why do you run `./busybox -d /usr/lib/mkinitramfs-ll/usr/` which is not necessary when using a dynamic busybox binary? This is the issue here. When using a dynamic binary you just to run `mkinitramfs-ll.$SHELL $ARGUMENTS` without changing directory and all!
Which `./busybox` are using? you mean `/usr/share/mkinitramfs-ll/scripts/busybox.sh`? If so, that script is only used to build a static binary. If it's not the case, the script should be fixed.

God, why is there so many step to build a initramfs when using a dynamic busybox binary when you only need to run a single script?!

**Comment by tokiclover** [comment]
I see, `scripts/busybox.sh` is outdated and you're using it... it fails to properly setup a sane configuration and build a static busybox.
SOLUTION: either remove busybox entierly which is not needed because I don't feel like wasting too much time fixing it. Let's see what I can do about it.

**Comment by szorfein** [comment]
yep i mean /usr/share/mkinitramfs-ll/scripts/busybox.sh, what else.  
Seriously, i don't know why busybox.sh doesn't work. 
I just launch you script...
I will give you the 10 last lines from.

    LINK busybox_unstripped
    Static linking against glibc, can'use --gc-sections
    Tryng libraries: crypt m
    Library crypt is not needed, excluding it
    Library m is needed, can't exclude it (yet)
   Final link with: m

**Comment by tokiclover** [comment]
Yes... however the configuration fails when not using `-m` switch. I am looking at it right now to see what I can do about it. That's why the minimal applets required are not builded.

**Comment by tokiclover** [comment]
Well, b2e36fd fixed building a static busyboxy binary. **WARING:*** You do *not* have to build a binary each time! build one if necessary and then rebuild another only if updating to a new version.

**Comment by szorfein** [comment]
Nice, it seem to work, compile and generate initramfs. good night )

**Pull request closed without merging**
